apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-components
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hryze/kakeibo-app-kubernetes.git
    targetRevision: main
    path: system-components/applications/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
