apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
patchesStrategicMerge:
- deployment/user-deployment.yaml
- externalsecret/user-secret.yaml
- hpa/user-hpa.yaml
- ingress/user-alb-ingress.yaml
- pdb/user-pdb.yaml
- service/user-service.yaml
commonLabels:
  app: user
images:
- name: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/user-rest-service
  newTag: release.ac2ae8b86146e81a7f496d1737f80689b95f8af9
configMapGenerator:
- literals:
  - ALLOWED_ORIGIN=https://www.shakepiper.com
  - COOKIE_DOMAIN=shakepiper.com
  - ACCOUNT_HOST=account-service.default.svc.cluster.local
  name: user-configmap
