apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
patchesStrategicMerge:
- deployment/user-deployment.yaml
- externalsecret/user-secret.yaml
- hpa/user-hpa.yaml
- ingress/user-alb-ingress.yaml
- pdb/user-pdb.yaml
- service/user-service.yaml
commonLabels:
  app: user
images:
- name: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/user-rest-service
  newTag: release.a4c5a54dbab3a3a096e0582a4ba692f2d8e4a4b9
configMapGenerator:
- literals:
  - GO_ENV=prod
  - PROD_SERVER_PORT=8080
  - PROD_CORS_ALLOWED_ORIGINS=https://www.shakepiper.com
  - PROD_COOKIE_NAME=prod_session_id
  - PROD_COOKIE_DOMAIN=shakepiper.com
  - PROD_COOKIE_SECURE=true
  - PROD_COOKIE_EXPIRATION=2592000s
  - PROD_MYSQL_MAX_CONN=25
  - PROD_MYSQL_MAX_IDLE=25
  - PROD_MYSQL_MAX_CONN_LIFETIME=300s
  - PROD_REDIS_MAX_CONN=25
  - PROD_REDIS_MAX_IDLE=25
  - PROD_REDIS_MAX_CONN_LIFETIME=300s
  - PROD_ACCOUNT_HOST=account-service.default.svc.cluster.local
  - PROD_ACCOUNT_PORT=8081
  name: user-configmap
