apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
patchesStrategicMerge:
- deployment/user-deployment.yaml
- externalsecret/user-secret.yaml
- hpa/user-hpa.yaml
- ingress/user-alb-ingress.yaml
- pdb/user-pdb.yaml
- service/user-service.yaml
commonLabels:
  app: user
images:
- name: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/user-rest-service
  newTag: release.56030f55ec63d688970ce32fdd4cd1a130d21605
configMapGenerator:
- literals:
  - ALLOWED_ORIGIN=https://www.shakepiper.com
  - COOKIE_DOMAIN=shakepiper.com
  - ACCOUNT_HOST=account-service.default.svc.cluster.local
  name: user-configmap
