apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  admin.enabled: "false"
  url: https://argocd.shakepiper.com
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: 5d13db2dace324a0561f
          clientSecret: $dex.github.clientSecret
          orgs:
            - name: shakepiper
              teams:
               - sre-team
