apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  backendType: secretsManager
  data:
    - key: argocd-secret
      name: dex.github.clientSecret
      property: dex_github_clientSecret
    - key: argocd-secret
      name: server.secretkey
      property: server_secretkey
