apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
patchesStrategicMerge:
- deployment/account-deployment.yaml
- externalsecret/account-secret.yaml
- hpa/account-hpa.yaml
- ingress/account-alb-ingress.yaml
- pdb/account-pdb.yaml
- service/account-service.yaml
commonLabels:
  app: account
images:
- name: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/account-rest-service
  newTag: release.d757671158ef23360e5faec851826d2b76f6d525
configMapGenerator:
- literals:
  - GO_ENV=prod
  - PROD_SERVER_PORT=8081
  - PROD_CORS_ALLOWED_ORIGINS=https://www.shakepiper.com
  - PROD_COOKIE_NAME=prod_session_id
  - PROD_MYSQL_MAX_CONN=25
  - PROD_MYSQL_MAX_IDLE=25
  - PROD_MYSQL_MAX_CONN_LIFETIME=300s
  - PROD_REDIS_MAX_CONN=25
  - PROD_REDIS_MAX_IDLE=25
  - PROD_REDIS_MAX_CONN_LIFETIME=300s
  - PROD_USER_HOST=user-service.default.svc.cluster.local
  - PROD_USER_PORT=8080
  - PROD_TODO_HOST=todo-service.default.svc.cluster.local
  - PROD_TODO_PORT=8082
  name: account-configmap
