apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../bases
patchesStrategicMerge:
- deployment/todo-deployment.yaml
- externalsecret/todo-secret.yaml
- hpa/todo-hpa.yaml
- ingress/todo-alb-ingress.yaml
- pdb/todo-pdb.yaml
- service/todo-service.yaml
commonLabels:
  app: todo
images:
- name: 048246832408.dkr.ecr.ap-northeast-1.amazonaws.com/todo-rest-service
  newTag: release.49279938440a094a9dd6a2641dbb233508b00c4e
configMapGenerator:
- literals:
  - GO_ENV="prod"
  - PROD_SERVER_PORT=8082
  - PROD_CORS_ALLOWED_ORIGINS="https://www.shakepiper.com"
  - PROD_COOKIE_NAME="prod_session_id"
  - PROD_MYSQL_MAX_CONN=25
  - PROD_MYSQL_MAX_IDLE=25
  - PROD_MYSQL_MAX_CONN_LIFETIME="300s"
  - PROD_REDIS_MAX_CONN=25
  - PROD_REDIS_MAX_IDLE=25
  - PROD_REDIS_MAX_CONN_LIFETIME="300s"
  - PROD_USER_HOST="user-service.default.svc.cluster.local"
  - PROD_USER_PORT=8080
  - PROD_ACCOUNT_HOST="account-service.default.svc.cluster.local"
  - PROD_ACCOUNT_PORT=8081
  name: todo-configmap
