apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/godaddy/kubernetes-external-secrets/6.0.0/charts/kubernetes-external-secrets/crds/kubernetes-client.io_externalsecrets_crd.yaml
  - serviceaccount/external-secrets.yaml
  - clusterrole/external-secrets.yaml
  - clusterrolebinding/external-secrets.yaml
  - clusterrolebinding/external-secrets-auth.yaml
  - service/external-secrets.yaml
  - deployment/external-secrets.yaml
