apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment/todo-deployment.yaml
  - externalsecret/todo-secret.yaml
  - hpa/todo-hpa.yaml
  - ingress/todo-alb-ingress.yaml
  - pdb/todo-pdb.yaml
  - service/todo-service.yaml
