apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: todo-secret
  labels:
    app: todo
spec:
  backendType: secretsManager
  data:
    - key: todo-db-dsn-secret
      name: PROD_MYSQL_DSN
      property: mysql_dsn
    - key: todo-db-dsn-secret
      name: PROD_REDIS_DSN
      property: redis_dsn
