apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-rest-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hryze/kakeibo-app-kubernetes.git
    targetRevision: main
    path: api/todo-rest-service/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
